### ISSUE TITLE
Trying on RaspberryPi 4 (4GB RAM)

### ISSUE THREAD

**Issue by HoSnoopy** [roborg-codes/telegram-mastodon-bridge#4]
I have no experience in docker. I tried your receipt, but it seems not to work.
I can find a logfile in /var/lib/docker/containers/<id>/<id>.log, which says:
{"log":"Traceback (most recent call last):\n","stream":"stderr","time":"2022-06-06T19:44:38.795110146Z"}
{"log":"  File \"./bot.py\", line 6, in \u003cmodule\u003e\n","stream":"stderr","time":"2022-06-06T19:44:38.795238609Z"}
{"log":"    from bridge.bridge import Bridge\n","stream":"stderr","time":"2022-06-06T19:44:38.795325071Z"}
{"log":"  File \"/bot/bridge/bridge.py\", line 16, in \u003cmodule\u003e\n","stream":"stderr","time":"2022-06-06T19:44:38.795346608Z"}
{"log":"    class Bridge():\n","stream":"stderr","time":"2022-06-06T19:44:38.795599088Z"}
{"log":"  File \"/bot/bridge/bridge.py\", line 84, in Bridge\n","stream":"stderr","time":"2022-06-06T19:44:38.795656865Z"}
{"log":"    def __send_status(self, text: List[str], media: Optional[str | bytes] = None, mime: Optional[str] = None) -\u003e None:\n","stream":"stderr","time":"2022-06-06T19:44:38.795819902Z"}
{"log":"TypeError: unsupported operand type(s) for |: 'type' and 'type'\n","stream":"stderr","time":"2022-06-06T19:44:38.79591392Z"}

No idea.. :)

**Comment by Mrs-Feathers** [comment]
i have the same error in my logs when doing "docker logs"
